--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/skh6075/proxy-thread
build-by-default: true
branches:
- main
projects:
  proxy-thread:
    path: ""
    model: virion
    type: library
...
